CREATE TABLE LIBRARY (
  ID INTEGER PRIMARY KEY,
  NAME TEXT NOT NULL,
  ROOT TEXT NOT NULL
);
CREATE TABLE TITLE (
  ID INTEGER PRIMARY KEY,
  NAME TEXT NOT NULL,
  URL TEXT NOT NULL,
  CREATED_AT TEXT NOT NULL,
  UPDATED_AT TEXT,
  LIBRARY_ID TEXT NOT NULL,
  FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY (ID)
);
CREATE INDEX idx__title__library_id on TITLE (LIBRARY_ID);
CREATE TABLE BOOK (
  ID INTEGER PRIMARY KEY,
  NAME TEXT NOT NULL,
  URL TEXT NOT NULL,
  CREATED_AT TEXT NOT NULL,
  UPDATED_AT TEXT NOT NULL,
  PAGE_COUNT INTEGER NOT NULL,
  TITLE_ID TEXT NOT NULL,
  LIBRARY_ID TEXT NOT NULL,
  FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY (ID),
  FOREIGN KEY (TITLE_ID) REFERENCES TITLE (ID)
);
CREATE INDEX idx__book__title_id on BOOK (TITLE_ID);
CREATE INDEX idx__book__library_id on BOOK (LIBRARY_ID);
CREATE TABLE PAGE (
  FILE_NAME TEXT NOT NULL,
  MEDIA_TYPE TEXT NOT NULL,
  NUMBER INTEGER NOT NULL,
  BOOK_ID TEXT NOT NULL,
  WIDTH INTEGER NOT NULL,
  HEIGHT INTEGER NOT NULL,
  PRIMARY KEY (BOOK_ID, NUMBER),
  FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
);